import os

WEBHOOK_PASSPHRASE=os.environ.get("WEBHOOK_PASSPHRASE")

BINANCE_ENABLED=os.environ.get("BINANCE_ENABLED")

BINANCE_TESTNET=os.environ.get("BINANCE_TESTNET")

BINANCE_API_KEY=os.environ.get("API_KEY")
BINANCE_API_SECRET=os.environ.get("API_SECRET")